# Generated by Django 4.1.1 on 2022-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
