# Generated by Django 4.1 on 2022-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=5,
            ),
        ),
    ]
